version: "3.7"
services:
  mysql-docker:
    image: mysql:8.0
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: dslist
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 1234567
    ports:
      - "3307:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin-docker:
    image: phpmyadmin/phpmyadmin
    container_name: dev-phpmyadmin
    environment:
      PMA_HOST: mysql-docker
      PMA_USER: root
      PMA_PASSWORD: 1234567
    ports:
      - "8081:80"
    depends_on:
      - mysql-docker
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
